### ISSUE TITLE
Arduino sketch

### ISSUE THREAD

**Issue by mills32** [DhrBaksteen/ArduinoOPL2.DosBox#1]
Sorry for being so silly, but... were is the arduino sketch I have to install for this to work?.

Thanks :).

**Comment by DhrBaksteen** [comment]
Hi,

The Arduino sketch will be part of the OPL2 board library which you can find here: https://github.com/DhrBaksteen/ArduinoOPL2. I was still testing this, so for now it's part of the DosBox_passthrough branch. I will prepare a new release for later today to include the sketch in the library since I didn't find any issues with it.

**Comment by mills32** [comment]
Oh thanks a lot. 
This is not really an issue, you should delete this.

**Comment by DhrBaksteen** [comment]
New release v1.4.3 is now available; closing this issue.
